#!/usr/bin/env node
/**
 * Regenerate src/glyphs-ja.json — the Japanese line as SVG path outlines.
 *
 * WHY THIS EXISTS
 * An SVG served through camo can only use fonts installed on the *viewer's*
 * machine. Anyone without a CJK font would see `コード王におれはなる` as tofu
 * boxes (□□□□□□□□□□), permanently, on the profile README. So the display line
 * is baked to <path> data at build time and the result is committed.
 *
 * Only run this if you change the wording. Requires network + one dev package:
 *
 *   npm i -D opentype.js && npm run glyphs
 *
 * LICENSING
 * Noto Sans JP is SIL OFL, which permits modification and embedding. We ship
 * only the *outlines* of the glyphs we use — the font binary is downloaded to a
 * temp file and never committed or redistributed. Per the OFL reserved-name
 * clause, do not call the output "Noto".
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'glyphs-ja.json');

const TEXT = process.argv[2] || 'コード王におれはなる！！！';
const SIZE = 100;   // reference em; the renderer scales from this
const WEIGHT = 900;

// Google Fonts serves a different format per User-Agent. This ancient Android
// string is the one that still yields plain TrueType (modern UAs get woff2,
// which opentype.js cannot parse).
const UA_TTF = 'Mozilla/5.0 (Linux; U; Android 2.3.5) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1';

const cssUrl = `https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@${WEIGHT}&text=${encodeURIComponent(TEXT)}`;
const css = await (await fetch(cssUrl, { headers: { 'user-agent': UA_TTF } })).text();
const fontUrl = css.match(/https:\/\/[^)]+/)?.[0];
if (!fontUrl) throw new Error(`no font url in CSS response:\n${css}`);

const buf = Buffer.from(await (await fetch(fontUrl)).arrayBuffer());
if (buf.readUInt32BE(0) !== 0x00010000 && buf.subarray(0, 4).toString() !== 'true') {
  throw new Error(`expected TrueType, got magic ${buf.subarray(0, 4).toString('hex')} — the UA trick may have stopped working`);
}
const tmp = path.join(os.tmpdir(), `notosansjp-subset-${Date.now()}.ttf`);
fs.writeFileSync(tmp, buf);

let opentype;
try { opentype = (await import('opentype.js')).default; }
catch { console.error('! opentype.js not installed — run: npm i -D opentype.js'); process.exit(1); }

const font = opentype.parse(fs.readFileSync(tmp).buffer.slice(0));
const p = font.getPath(TEXT, 0, 0, SIZE);
const box = p.getBoundingBox();

fs.writeFileSync(OUT, JSON.stringify({
  _note: 'Generated by scripts/gen-glyphs.mjs from Noto Sans JP Black (SIL OFL). Outlines only — no font binary is redistributed.',
  size: SIZE,
  text: TEXT,
  advance: +font.getAdvanceWidth(TEXT, SIZE).toFixed(2),
  box: { x1: +box.x1.toFixed(2), y1: +box.y1.toFixed(2), x2: +box.x2.toFixed(2), y2: +box.y2.toFixed(2) },
  d: p.toPathData(2),
}));
fs.unlinkSync(tmp);

console.log(`✓ ${TEXT}`);
console.log(`  ${[...TEXT].length} glyphs · advance ${font.getAdvanceWidth(TEXT, SIZE).toFixed(0)}@${SIZE}px · ${(fs.statSync(OUT).size / 1024).toFixed(1)} KB → src/glyphs-ja.json`);
console.log(`  at 48px the line is ${(font.getAdvanceWidth(TEXT, SIZE) * 0.48).toFixed(0)}px wide (board is 1055px)`);
